import { useRef, useState } from 'react'
import { routines } from '../data/routines'
import { clearStoredActiveProfileId } from '../db/activeProfile'
import { clearAllData, deleteProfile, exportData, importData, saveSettings, updateProfile } from '../db/database'
import type { Profile, Settings } from '../types'
import { PROFILE_COLORS, avatarTextColor, profileInitial } from './ProfilesView'

export function ParentView({settings,profileId,profiles,onChange,onDataChange}:{settings:Settings;profileId:string;profiles:Profile[];onChange:(s:Settings)=>void;onDataChange:()=>void}) {
  const [unlocked,setUnlocked]=useState(false); const [holding,setHolding]=useState(false); const [message,setMessage]=useState(''); const timer=useRef<number>(undefined); const file=useRef<HTMLInputElement>(null)
  const start=()=>{setHolding(true);timer.current=window.setTimeout(()=>{setUnlocked(true);setHolding(false)},3000)}; const stop=()=>{window.clearTimeout(timer.current);setHolding(false)}
  const update=async(next:Settings)=>{await saveSettings(profileId,next);onChange(next)}
  const move=async(id:string,direction:-1|1)=>{const order=[...settings.order];const from=order.indexOf(id);const to=from+direction;if(to<0||to>=order.length)return;[order[from],order[to]]=[order[to],order[from]];await update({...settings,order})}
  const download=async()=>{const data=await exportData();const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`zdrowe-rutyny-${data.exportedAt.slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setMessage('Eksport jest gotowy.')}
  const upload=async(event:React.ChangeEvent<HTMLInputElement>)=>{const selected=event.target.files?.[0];if(!selected)return;try{await importData(JSON.parse(await selected.text()));setMessage('Dane zostały zaimportowane.');onDataChange()}catch(error){setMessage(error instanceof Error?error.message:'Nie udało się odczytać pliku.')}finally{event.target.value=''}}
  const clear=async()=>{if(!confirm('Czy na pewno chcesz usunąć wszystkie dane?'))return;if(!confirm('To ostatnie potwierdzenie. Tej operacji nie można cofnąć.'))return;await clearAllData();clearStoredActiveProfileId();setMessage('Wszystkie lokalne dane zostały usunięte.');onDataChange()}
  if(!unlocked)return <section className="locked"><div><span aria-hidden="true">🔒</span><h1>Strefa rodzica</h1><p>Przytrzymaj przycisk przez 3 sekundy.</p><button className={`hold-button ${holding?'holding':''}`} onPointerDown={start} onPointerUp={stop} onPointerLeave={stop} onKeyDown={e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat)start()}} onKeyUp={stop} aria-label="Przytrzymaj przez 3 sekundy, aby otworzyć strefę rodzica">{holding?'Trzymaj…':'Przytrzymaj, aby wejść'}</button></div></section>
  return <section><div className="page-title"><h1>Strefa rodzica</h1><p>Ustaw rutyny i zarządzaj danymi zapisanymi na tym urządzeniu.</p></div><div className="parent-panel"><h2>Profile dzieci</h2>{profiles.map(p=><ProfileRow key={p.id} profile={p} canDelete={profiles.length>1} onSaved={onDataChange}/>)}<p className="hint">Nowe profile dodasz na ekranie wyboru profilu (awatar w górnym pasku).</p></div><div className="parent-panel"><h2>Rutyny i kolejność</h2>{settings.order.map((id,index)=>{const r=routines.find(item=>item.id===id)!;return <div className="setting-row" key={id}><label><input type="checkbox" checked={settings.active[id]!==false} onChange={e=>update({...settings,active:{...settings.active,[id]:e.target.checked}})} aria-label={`${settings.active[id]!==false?'Wyłącz':'Włącz'} rutynę ${r.tytul}`}/><span>{r.numer}. {r.tytul}</span></label><div><button disabled={index===0} onClick={()=>move(id,-1)} aria-label={`Przesuń ${r.tytul} wyżej`}>↑</button><button disabled={index===settings.order.length-1} onClick={()=>move(id,1)} aria-label={`Przesuń ${r.tytul} niżej`}>↓</button></div></div>})}</div><div className="parent-panel"><h2>Kopia danych</h2><div className="action-grid"><button onClick={download}>Eksportuj JSON</button><button onClick={()=>file.current?.click()}>Importuj JSON</button><input ref={file} className="visually-hidden" type="file" accept="application/json,.json" onChange={upload}/><button className="danger" onClick={clear}>Usuń wszystkie dane</button></div>{message&&<p role="status" className="message">{message}</p>}</div><div className="parent-panel"><h2>Jak zainstalować aplikację</h2><p><strong>Windows (Edge/Chrome):</strong> ikona instalacji przy pasku adresu albo menu przeglądarki → Zainstaluj Akademia Super Zdrowia.</p><p><strong>Android (Chrome):</strong> menu ⋮ → Zainstaluj aplikację, albo zaakceptuj „Dodaj do ekranu głównego”.</p><p><strong>iPhone (Safari):</strong> Udostępnij → Do ekranu początkowego → Dodaj.</p></div></section>
}

function ProfileRow({profile,canDelete,onSaved}:{profile:Profile;canDelete:boolean;onSaved:()=>void}) {
  const [name,setName]=useState(profile.name)
  const saveName=async()=>{const trimmed=name.trim();if(!trimmed||trimmed===profile.name){setName(profile.name);return}await updateProfile({...profile,name:trimmed});onSaved()}
  const setColor=async(color:string)=>{await updateProfile({...profile,color});onSaved()}
  const remove=async()=>{if(!confirm(`Usunąć profil ${profile.name} razem z historią i punktami? Tej operacji nie można cofnąć.`))return;await deleteProfile(profile.id);onSaved()}
  return <div className="profile-row"><span className="profile-avatar small" style={{background:profile.color,color:avatarTextColor(profile.color)}} aria-hidden="true">{profileInitial(profile.name)}</span><input value={name} onChange={e=>setName(e.target.value)} onBlur={saveName} onKeyDown={e=>{if(e.key==='Enter')(e.target as HTMLInputElement).blur()}} maxLength={20} aria-label={`Imię profilu ${profile.name}`}/><div className="color-row">{PROFILE_COLORS.map(c=><button key={c} type="button" className={`color-dot ${c===profile.color?'selected':''}`} style={{background:c}} onClick={()=>setColor(c)} aria-label={`Zmień kolor profilu ${profile.name}`}/>)}</div><button className="danger" disabled={!canDelete} title={canDelete?undefined:'Nie można usunąć ostatniego profilu'} onClick={remove} aria-label={`Usuń profil ${profile.name}`}>Usuń</button></div>
}
